from typing import Any, overload

# This file is auto-generated by the openc3 extension to provide intellisense
# NOTE: any modifications to this file will not persist between plugin loads
from typing import Any, overload

# Define the 'cmd' function signature
def cmd(target: str, command: str, **kwargs: Any) -> Any:
    """
    Sends a command through the COSMOS system.
    """
    ...

# Define the 'tlm' function signature
def tlm(packet: str, item: str) -> Any:
    """
    Retrieves telemetry from the COSMOS system.
    """
    ...

# Add any other globally injected functions here
# def wait(seconds: float) -> None: ...
